INSERT INTO ALUNO(nome)
VALUES('João Pedro');

INSERT INTO ALUNO(nome)
VALUES('Gabriella');

INSERT INTO PROFESSOR(nome)
VALUES('Marcelo');

INSERT INTO PROFESSOR(nome)
VALUES('Rodrigo');

INSERT INTO PROVA(nome)
VALUES('Spring');

INSERT INTO PROVA(nome)
VALUES('SQL');